export interface FoodItem {
  name: string
  calories: number
  serving: string
}

export const FOOD_DATABASE: FoodItem[] = [

  // ── Chicken ────────────────────────────────────────────────────────
  { name: 'Chicken fillet', calories: 165, serving: '100g (cooked)' },
  { name: 'Chicken breast', calories: 165, serving: '100g (cooked)' },
  { name: 'Chicken schnitzel', calories: 220, serving: '100g (fried)' },
  { name: 'Chicken schnitzel (baked)', calories: 185, serving: '100g' },
  { name: 'Chicken thigh', calories: 209, serving: '100g (cooked)' },
  { name: 'Chicken drumstick', calories: 172, serving: '100g (cooked)' },
  { name: 'Chicken wings', calories: 203, serving: '100g (cooked)' },
  { name: 'Rotisserie chicken', calories: 190, serving: '100g' },
  { name: 'Chicken nuggets', calories: 296, serving: '6 pieces (96g)' },
  { name: 'Fried chicken', calories: 246, serving: '100g' },
  { name: 'Chicken stir fry', calories: 150, serving: '100g' },
  { name: 'Chicken soup', calories: 45, serving: '1 cup (240ml)' },
  { name: 'Chicken shawarma', calories: 250, serving: '100g' },
  { name: 'Chicken burger', calories: 350, serving: '1 burger' },
  { name: 'Grilled chicken', calories: 165, serving: '100g' },

  // ── Beef ───────────────────────────────────────────────────────────
  { name: 'Ground beef 80%', calories: 254, serving: '100g (cooked)' },
  { name: 'Ground beef lean 90%', calories: 196, serving: '100g (cooked)' },
  { name: 'Beef steak', calories: 271, serving: '100g (grilled)' },
  { name: 'Beef sirloin', calories: 207, serving: '100g (grilled)' },
  { name: 'Beef ribeye', calories: 291, serving: '100g (grilled)' },
  { name: 'Beef tenderloin', calories: 219, serving: '100g (grilled)' },
  { name: 'Beef entrecote', calories: 275, serving: '100g (grilled)' },
  { name: 'Hamburger patty', calories: 295, serving: '100g (cooked)' },
  { name: 'Meatballs', calories: 250, serving: '100g (cooked)' },
  { name: 'Beef stew', calories: 160, serving: '100g' },
  { name: 'Roast beef', calories: 215, serving: '100g' },

  // ── Lamb & Veal ────────────────────────────────────────────────────
  { name: 'Lamb chop', calories: 294, serving: '100g (cooked)' },
  { name: 'Lamb kebab', calories: 236, serving: '100g' },
  { name: 'Veal', calories: 196, serving: '100g (cooked)' },

  // ── Pork ───────────────────────────────────────────────────────────
  { name: 'Pork chop', calories: 231, serving: '100g (cooked)' },
  { name: 'Bacon', calories: 541, serving: '100g (fried)' },
  { name: 'Bacon strip', calories: 43, serving: '1 strip (8g)' },
  { name: 'Ham', calories: 145, serving: '100g' },
  { name: 'Sausage', calories: 301, serving: '100g' },
  { name: 'Hot dog (frankfurter)', calories: 150, serving: '1 (57g)' },
  { name: 'Salami', calories: 336, serving: '100g' },
  { name: 'Pepperoni', calories: 494, serving: '100g' },

  // ── Turkey ─────────────────────────────────────────────────────────
  { name: 'Turkey breast', calories: 135, serving: '100g (cooked)' },
  { name: 'Turkey schnitzel', calories: 200, serving: '100g (cooked)' },
  { name: 'Turkey mince', calories: 170, serving: '100g (cooked)' },

  // ── Fish & Seafood ─────────────────────────────────────────────────
  { name: 'Salmon', calories: 208, serving: '100g (cooked)' },
  { name: 'Salmon fillet', calories: 208, serving: '100g (cooked)' },
  { name: 'Tuna (canned)', calories: 116, serving: '100g' },
  { name: 'Tuna steak', calories: 184, serving: '100g (grilled)' },
  { name: 'Sea bass', calories: 124, serving: '100g (cooked)' },
  { name: 'Tilapia', calories: 129, serving: '100g (cooked)' },
  { name: 'Cod', calories: 105, serving: '100g (cooked)' },
  { name: 'Sardines', calories: 208, serving: '100g' },
  { name: 'Mackerel', calories: 205, serving: '100g (cooked)' },
  { name: 'Trout', calories: 190, serving: '100g (cooked)' },
  { name: 'Shrimp', calories: 99, serving: '100g (cooked)' },
  { name: 'Crab', calories: 97, serving: '100g (cooked)' },
  { name: 'Lobster', calories: 89, serving: '100g (cooked)' },
  { name: 'Calamari (fried)', calories: 175, serving: '100g' },
  { name: 'Fish fillet (fried)', calories: 196, serving: '100g' },
  { name: 'Fish and chips', calories: 595, serving: '1 portion (300g)' },
  { name: 'Gefilte fish', calories: 90, serving: '1 piece (90g)' },

  // ── Eggs ───────────────────────────────────────────────────────────
  { name: 'Egg (boiled)', calories: 78, serving: '1 large (50g)' },
  { name: 'Egg (fried)', calories: 90, serving: '1 large' },
  { name: 'Egg (scrambled)', calories: 91, serving: '1 large' },
  { name: 'Omelet (2 eggs)', calories: 190, serving: '2 eggs + oil' },
  { name: 'Egg white', calories: 17, serving: '1 large' },

  // ── Legumes & Plant Protein ─────────────────────────────────────────
  { name: 'Tofu', calories: 76, serving: '100g' },
  { name: 'Lentils', calories: 116, serving: '100g (cooked)' },
  { name: 'Chickpeas', calories: 164, serving: '100g (cooked)' },
  { name: 'Black beans', calories: 132, serving: '100g (cooked)' },
  { name: 'Kidney beans', calories: 127, serving: '100g (cooked)' },
  { name: 'Edamame', calories: 121, serving: '100g' },
  { name: 'Tempeh', calories: 193, serving: '100g' },

  // ── Dairy ──────────────────────────────────────────────────────────
  { name: 'Whole milk', calories: 61, serving: '100ml' },
  { name: 'Skim milk', calories: 35, serving: '100ml' },
  { name: 'Greek yogurt (0%)', calories: 59, serving: '100g' },
  { name: 'Greek yogurt (2%)', calories: 73, serving: '100g' },
  { name: 'Yogurt (full fat)', calories: 97, serving: '100g' },
  { name: 'Cheddar cheese', calories: 402, serving: '100g' },
  { name: 'Mozzarella', calories: 280, serving: '100g' },
  { name: 'Feta cheese', calories: 264, serving: '100g' },
  { name: 'Cottage cheese', calories: 98, serving: '100g' },
  { name: 'Ricotta', calories: 174, serving: '100g' },
  { name: 'Parmesan', calories: 431, serving: '100g' },
  { name: 'Cream cheese', calories: 342, serving: '100g' },
  { name: 'Butter', calories: 102, serving: '1 tbsp (14g)' },
  { name: 'Heavy cream', calories: 340, serving: '100ml' },
  { name: 'Sour cream', calories: 193, serving: '100g' },
  { name: 'Whipped cream', calories: 257, serving: '100g' },
  { name: 'Ice cream', calories: 207, serving: '100g' },
  { name: 'Cheese slice (processed)', calories: 300, serving: '100g' },

  // ── Grains & Rice ──────────────────────────────────────────────────
  { name: 'White rice', calories: 130, serving: '100g (cooked)' },
  { name: 'Brown rice', calories: 111, serving: '100g (cooked)' },
  { name: 'Basmati rice', calories: 121, serving: '100g (cooked)' },
  { name: 'Jasmine rice', calories: 130, serving: '100g (cooked)' },
  { name: 'Pasta (plain)', calories: 131, serving: '100g (cooked)' },
  { name: 'Pasta with tomato sauce', calories: 160, serving: '100g' },
  { name: 'Pasta carbonara', calories: 230, serving: '100g' },
  { name: 'Mac and cheese', calories: 164, serving: '100g' },
  { name: 'Oatmeal', calories: 71, serving: '100g (cooked)' },
  { name: 'Quinoa', calories: 120, serving: '100g (cooked)' },
  { name: 'Couscous', calories: 112, serving: '100g (cooked)' },
  { name: 'Granola', calories: 471, serving: '100g' },
  { name: 'Cornflakes', calories: 357, serving: '100g' },
  { name: 'Muesli', calories: 370, serving: '100g' },

  // ── Bread & Baked ──────────────────────────────────────────────────
  { name: 'White bread', calories: 265, serving: '100g (≈3 slices)' },
  { name: 'Whole wheat bread', calories: 247, serving: '100g (≈3 slices)' },
  { name: 'Sourdough bread', calories: 274, serving: '100g' },
  { name: 'Rye bread', calories: 259, serving: '100g' },
  { name: 'Baguette', calories: 270, serving: '100g' },
  { name: 'Pita bread', calories: 275, serving: '1 medium (60g)' },
  { name: 'Bagel', calories: 245, serving: '1 medium (98g)' },
  { name: 'Croissant', calories: 406, serving: '1 medium (57g)' },
  { name: 'Tortilla (flour)', calories: 218, serving: '1 medium (45g)' },
  { name: 'Tortilla (corn)', calories: 209, serving: '1 medium (44g)' },
  { name: 'Pretzel', calories: 380, serving: '100g' },
  { name: 'Crackers', calories: 430, serving: '100g' },
  { name: 'Rice cake', calories: 387, serving: '100g (≈10 cakes)' },
  { name: 'Breadstick', calories: 412, serving: '100g' },
  { name: 'Toast', calories: 313, serving: '100g' },
  { name: 'English muffin', calories: 227, serving: '1 muffin (57g)' },

  // ── Breakfast ──────────────────────────────────────────────────────
  { name: 'Pancake', calories: 227, serving: '100g (≈2 medium)' },
  { name: 'Waffle', calories: 291, serving: '1 round (75g)' },
  { name: 'French toast', calories: 229, serving: '100g' },
  { name: 'Cereal with milk', calories: 160, serving: '1 bowl (240ml milk + 30g cereal)' },
  { name: 'Granola with milk', calories: 230, serving: '1 bowl' },
  { name: 'Avocado toast', calories: 280, serving: '2 slices bread + 1/2 avocado' },
  { name: 'Shakshuka', calories: 180, serving: '1 serving (250g)' },

  // ── Salads & Light Meals ───────────────────────────────────────────
  { name: 'Israeli salad', calories: 40, serving: '100g' },
  { name: 'Caesar salad', calories: 120, serving: '100g (no croutons)' },
  { name: 'Caesar salad (full)', calories: 470, serving: '1 serving (350g)' },
  { name: 'Greek salad', calories: 90, serving: '100g' },
  { name: 'Tabbouleh', calories: 70, serving: '100g' },
  { name: 'Tuna salad', calories: 150, serving: '100g' },
  { name: 'Chicken salad', calories: 180, serving: '100g' },
  { name: 'Egg salad', calories: 150, serving: '100g' },

  // ── Soups ──────────────────────────────────────────────────────────
  { name: 'Chicken soup', calories: 45, serving: '1 cup (240ml)' },
  { name: 'Tomato soup', calories: 74, serving: '1 cup (240ml)' },
  { name: 'Lentil soup', calories: 130, serving: '1 cup (240ml)' },
  { name: 'Minestrone', calories: 82, serving: '1 cup (240ml)' },
  { name: 'Onion soup', calories: 57, serving: '1 cup (240ml)' },

  // ── Fruits ─────────────────────────────────────────────────────────
  { name: 'Apple', calories: 95, serving: '1 medium (182g)' },
  { name: 'Banana', calories: 105, serving: '1 medium (118g)' },
  { name: 'Orange', calories: 62, serving: '1 medium (131g)' },
  { name: 'Grapes', calories: 69, serving: '100g' },
  { name: 'Strawberries', calories: 33, serving: '100g' },
  { name: 'Watermelon', calories: 30, serving: '100g' },
  { name: 'Mango', calories: 60, serving: '100g' },
  { name: 'Pineapple', calories: 50, serving: '100g' },
  { name: 'Blueberries', calories: 57, serving: '100g' },
  { name: 'Raspberries', calories: 52, serving: '100g' },
  { name: 'Blackberries', calories: 43, serving: '100g' },
  { name: 'Avocado', calories: 160, serving: '100g' },
  { name: 'Peach', calories: 39, serving: '1 medium (150g)' },
  { name: 'Pear', calories: 57, serving: '1 medium (166g)' },
  { name: 'Melon', calories: 34, serving: '100g' },
  { name: 'Kiwi', calories: 61, serving: '1 medium (76g)' },
  { name: 'Lemon', calories: 17, serving: '1 medium (58g)' },
  { name: 'Pomegranate', calories: 83, serving: '100g' },
  { name: 'Dates', calories: 282, serving: '100g' },
  { name: 'Fig', calories: 74, serving: '100g' },
  { name: 'Plum', calories: 46, serving: '1 medium (66g)' },
  { name: 'Cherry', calories: 63, serving: '100g' },
  { name: 'Grapefruit', calories: 42, serving: '1/2 (123g)' },
  { name: 'Papaya', calories: 43, serving: '100g' },
  { name: 'Coconut (fresh)', calories: 354, serving: '100g' },

  // ── Vegetables ─────────────────────────────────────────────────────
  { name: 'Broccoli', calories: 34, serving: '100g' },
  { name: 'Cauliflower', calories: 25, serving: '100g' },
  { name: 'Carrot', calories: 41, serving: '100g' },
  { name: 'Cucumber', calories: 15, serving: '100g' },
  { name: 'Tomato', calories: 18, serving: '100g' },
  { name: 'Cherry tomatoes', calories: 18, serving: '100g' },
  { name: 'Spinach', calories: 23, serving: '100g' },
  { name: 'Lettuce', calories: 15, serving: '100g' },
  { name: 'Kale', calories: 49, serving: '100g' },
  { name: 'Potato (boiled)', calories: 77, serving: '100g' },
  { name: 'Potato (baked)', calories: 93, serving: '100g' },
  { name: 'Sweet potato', calories: 86, serving: '100g (baked)' },
  { name: 'Onion', calories: 40, serving: '100g' },
  { name: 'Red onion', calories: 40, serving: '100g' },
  { name: 'Bell pepper', calories: 31, serving: '100g' },
  { name: 'Mushrooms', calories: 22, serving: '100g' },
  { name: 'Eggplant', calories: 25, serving: '100g' },
  { name: 'Zucchini', calories: 17, serving: '100g' },
  { name: 'Corn', calories: 86, serving: '100g' },
  { name: 'Peas', calories: 81, serving: '100g' },
  { name: 'Celery', calories: 16, serving: '100g' },
  { name: 'Asparagus', calories: 20, serving: '100g' },
  { name: 'Green beans', calories: 31, serving: '100g' },
  { name: 'Cabbage', calories: 25, serving: '100g' },
  { name: 'Artichoke', calories: 47, serving: '100g' },
  { name: 'Beet', calories: 43, serving: '100g' },

  // ── Nuts & Seeds ───────────────────────────────────────────────────
  { name: 'Almonds', calories: 579, serving: '100g' },
  { name: 'Walnuts', calories: 654, serving: '100g' },
  { name: 'Cashews', calories: 553, serving: '100g' },
  { name: 'Peanuts', calories: 567, serving: '100g' },
  { name: 'Peanut butter', calories: 188, serving: '2 tbsp (32g)' },
  { name: 'Almond butter', calories: 196, serving: '2 tbsp (32g)' },
  { name: 'Sunflower seeds', calories: 584, serving: '100g' },
  { name: 'Chia seeds', calories: 486, serving: '100g' },
  { name: 'Flaxseeds', calories: 534, serving: '100g' },
  { name: 'Pistachios', calories: 560, serving: '100g' },
  { name: 'Pecans', calories: 691, serving: '100g' },
  { name: 'Macadamia nuts', calories: 718, serving: '100g' },
  { name: 'Trail mix', calories: 462, serving: '100g' },

  // ── Fast Food & Takeaway ───────────────────────────────────────────
  { name: 'Big Mac', calories: 550, serving: '1 burger' },
  { name: 'Cheeseburger', calories: 303, serving: '1 burger' },
  { name: 'Hamburger', calories: 254, serving: '1 burger' },
  { name: 'Double cheeseburger', calories: 461, serving: '1 burger' },
  { name: 'French fries (small)', calories: 230, serving: '1 small portion' },
  { name: 'French fries (medium)', calories: 365, serving: '1 medium portion' },
  { name: 'French fries (large)', calories: 490, serving: '1 large portion' },
  { name: 'Pizza (cheese)', calories: 266, serving: '1 slice (107g)' },
  { name: 'Pizza (pepperoni)', calories: 298, serving: '1 slice (107g)' },
  { name: 'Pizza (veggie)', calories: 235, serving: '1 slice (107g)' },
  { name: 'Hot dog', calories: 290, serving: '1 with bun' },
  { name: 'Burrito', calories: 490, serving: '1 medium (200g)' },
  { name: 'Taco', calories: 226, serving: '1 medium' },
  { name: 'Sushi roll', calories: 200, serving: '6 pieces (100g)' },
  { name: 'Sashimi', calories: 130, serving: '6 pieces (100g)' },
  { name: 'Pad Thai', calories: 300, serving: '100g' },
  { name: 'Fried rice', calories: 163, serving: '100g' },
  { name: 'Spring roll', calories: 130, serving: '1 piece (60g)' },

  // ── Snacks & Sweets ────────────────────────────────────────────────
  { name: 'Dark chocolate', calories: 598, serving: '100g' },
  { name: 'Milk chocolate', calories: 535, serving: '100g' },
  { name: 'Chocolate bar (Snickers)', calories: 488, serving: '100g' },
  { name: 'Potato chips', calories: 536, serving: '100g' },
  { name: 'Popcorn (air-popped)', calories: 387, serving: '100g' },
  { name: 'Popcorn (cinema, buttered)', calories: 460, serving: '100g' },
  { name: 'Cookie', calories: 480, serving: '100g' },
  { name: 'Donut (glazed)', calories: 269, serving: '1 donut (60g)' },
  { name: 'Muffin', calories: 430, serving: '1 medium (113g)' },
  { name: 'Brownie', calories: 466, serving: '100g' },
  { name: 'Cake (slice)', calories: 350, serving: '1 slice (80g)' },
  { name: 'Cheesecake', calories: 321, serving: '1 slice (80g)' },
  { name: 'Honey', calories: 304, serving: '100g' },
  { name: 'Jam', calories: 278, serving: '100g' },
  { name: 'Protein bar', calories: 200, serving: '1 bar (50g)' },
  { name: 'Granola bar', calories: 193, serving: '1 bar (47g)' },

  // ── Israeli / Mediterranean ────────────────────────────────────────
  { name: 'Hummus', calories: 166, serving: '100g' },
  { name: 'Falafel', calories: 333, serving: '100g (≈3 balls)' },
  { name: 'Tahini', calories: 595, serving: '100g' },
  { name: 'Shawarma (chicken)', calories: 250, serving: '100g' },
  { name: 'Shawarma (meat)', calories: 280, serving: '100g' },
  { name: 'Sabich', calories: 520, serving: '1 pita sandwich' },
  { name: 'Labneh', calories: 179, serving: '100g' },
  { name: 'Burekas (cheese)', calories: 370, serving: '1 piece (80g)' },
  { name: 'Burekas (potato)', calories: 340, serving: '1 piece (80g)' },
  { name: 'Bamba', calories: 570, serving: '100g' },
  { name: 'Bissli', calories: 460, serving: '100g' },
  { name: 'Krembo', calories: 115, serving: '1 krembo (35g)' },
  { name: 'Jachnun', calories: 310, serving: '1 piece (100g)' },
  { name: 'Malabi', calories: 150, serving: '1 serving (150g)' },
  { name: 'Kubbe', calories: 280, serving: '1 piece (100g)' },
  { name: 'Bourekita', calories: 200, serving: '1 piece (55g)' },
  { name: 'Hallah bread', calories: 290, serving: '100g' },
  { name: 'Techina sauce', calories: 306, serving: '100g (diluted)' },
  { name: 'Eggplant with tahini', calories: 120, serving: '100g' },

  // ── Beverages ──────────────────────────────────────────────────────
  { name: 'Coffee (black)', calories: 2, serving: '240ml' },
  { name: 'Espresso', calories: 5, serving: '30ml shot' },
  { name: 'Latte', calories: 190, serving: '480ml (grande)' },
  { name: 'Cappuccino', calories: 120, serving: '240ml' },
  { name: 'Flat white', calories: 150, serving: '240ml' },
  { name: 'Iced coffee (sweetened)', calories: 200, serving: '480ml' },
  { name: 'Orange juice', calories: 112, serving: '240ml' },
  { name: 'Apple juice', calories: 114, serving: '240ml' },
  { name: 'Coca-Cola', calories: 139, serving: '330ml can' },
  { name: 'Coca-Cola Zero', calories: 1, serving: '330ml can' },
  { name: 'Sprite', calories: 130, serving: '330ml can' },
  { name: 'Beer (regular)', calories: 153, serving: '330ml can' },
  { name: 'Beer (light)', calories: 103, serving: '330ml can' },
  { name: 'Red wine', calories: 125, serving: '150ml glass' },
  { name: 'White wine', calories: 121, serving: '150ml glass' },
  { name: 'Vodka', calories: 97, serving: '42ml shot' },
  { name: 'Whiskey', calories: 105, serving: '42ml shot' },
  { name: 'Smoothie (fruit)', calories: 120, serving: '240ml' },
  { name: 'Protein shake', calories: 160, serving: '1 scoop + 300ml water' },
  { name: 'Energy drink', calories: 110, serving: '250ml can' },
  { name: 'Limonana', calories: 130, serving: '300ml' },
  { name: 'Chocolate milk', calories: 158, serving: '240ml' },

  // ── Condiments & Oils ──────────────────────────────────────────────
  { name: 'Olive oil', calories: 119, serving: '1 tbsp (13.5ml)' },
  { name: 'Ketchup', calories: 30, serving: '2 tbsp (34g)' },
  { name: 'Mayonnaise', calories: 94, serving: '1 tbsp (14g)' },
  { name: 'Mustard', calories: 9, serving: '1 tsp (5g)' },
  { name: 'Soy sauce', calories: 8, serving: '1 tbsp (15ml)' },
  { name: 'Caesar dressing', calories: 78, serving: '2 tbsp (30g)' },
  { name: 'Ranch dressing', calories: 73, serving: '2 tbsp (30g)' },
  { name: 'Hot sauce', calories: 6, serving: '1 tbsp (15ml)' },
  { name: 'Guacamole', calories: 160, serving: '100g' },
  { name: 'Salsa', calories: 36, serving: '100g' },
]

export function searchFood(query: string, limit = 8): FoodItem[] {
  const q = query.toLowerCase().trim()
  if (q.length < 1) return []
  return FOOD_DATABASE
    .filter((f) => f.name.toLowerCase().includes(q))
    .sort((a, b) => {
      const aStarts = a.name.toLowerCase().startsWith(q)
      const bStarts = b.name.toLowerCase().startsWith(q)
      if (aStarts && !bStarts) return -1
      if (!aStarts && bStarts) return 1
      return a.name.localeCompare(b.name)
    })
    .slice(0, limit)
}
